var keyMirror = require('keymirror');

module.exports = keyMirror({
    NODE_CHANGED: null,
    NODE_REMOVED: null,
    NODE_MOUSEOVER: null,
    NODE_MOUSEOUT: null,
    NODE_ACTION_ADDNODE: null,
    NODE_ACTION_UPDATE_NODE: null,
    NODE_ACTION_ADD_CHILD_NODE: null,
    NODE_ACTION_ADD_NODE_AS_FIRST_CHILD: null,
    NODE_ACTION_ADD_NODE_AS_LAST_CHILD: null,
    NODE_ACTION_INSERT_NODE_BESIDE_SIBLING: null,
    NODE_ACTION_INSERT_NODE_BEFORE_SIBLING: null,
    NODE_ACTION_INSERT_NODE_AFTER_SIBLING: null
});